### ISSUE TITLE
Server monitoring for Minecraft servers non-functional

### ISSUE THREAD

**Issue by Antec187** [msniveau/discord-statusbot#8]
While setting up the bot, I added mcr and mcpe servers, I confirmed that the bot could scan and retrieved the correct information for the server. I then went ahead and shut the server down and waited. The bot never sent the formatted text to the channel indicating that the server was down. I did confirm with a Status command and reply that the bot detected that the server was not reachable.

**Comment by msniveau** [comment]
fixed that with the most recent updates
